added form for adding events
slava521/calendar-of-events pull request #5
Opened 2023-04-07 22:49 UTC by slava521

2023-04-08 20:44 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEventForm.tsx
> +                            disabled
думаю, должна быть возможность менять дату

2023-04-08 20:44 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEventForm.tsx
смотри что есть https://react-hook-form.com/

2023-04-08 21:13 UTC, slava521 commented on src/components/main/events/addEvent/AddEventForm.tsx
> +                            disabled
дата меняется в самом календаре

2023-04-08 21:22 UTC, slava521 commented on src/components/main/events/addEvent/AddEventForm.tsx
я хотел использовать добавление в виде формы, но это бы в разы усложнило задачу

2023-04-08 21:22 UTC, SanyaSemenov commented
В целом выглядит нормально. Осталось поправить замечания и реализовать хранения событий в localStorage

2023-04-08 21:26 UTC, SanyaSemenov requested changes

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEvent.tsx
> +        const eventInput = document.getElementById('eventInput') as HTMLInputElement;
в AddEventForm должен быть колбэк, который возвращал бы значение формы. Плохо так делать)
1. нехорошо из одного компонента стучаться к элементу другого
2. Это реакт, нужно по максимуму использовать его возможности (не стоит стучаться к DOM-элементам в принципе, если можно решить нормально)

Сделай так, чтобы можно было использовать примерно следующим образом `<AddEventForm onSumbit={this.handleSubmit} />`

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEventForm.tsx
> +                            value={dayjs(`${this.props.currentDate.currentMonth}.${this.props.currentDate.currentDay}.${this.props.currentDate.currentYear}`).locale('ru')}
Для такого большого выражения лучше добавить геттер
```typescript
get defaultDateValue() {
  return dayjs(`${this.props.currentDate.currentMonth}.${this.props.currentDate.currentDay}.${this.props.currentDate.currentYear}`).locale('ru');
}
```
```html
<DateField value={this.defaultDateValue} ...
```

2023-04-08 21:26 UTC, SanyaSemenov commented on src/state.ts
> +            let newEvent:ICalendarEvent = new class implements ICalendarEvent {
что это?) `new class implements ICalendarEvent`
Создай отдельный класс в отдельном файле
```typescript
export class CalendarEvent implements ICalendarEvent {
  constructor(date: string, event: string, id: number) {
    this.date = date;
    this.event = event;
    this.id = id
  }
  date: string;
  event: string;
  id: number;
}
```
а вообще зачем тут именно класс нужен? можно сделать `state.events` типа `Array< ICalendarEvent>`

2023-04-08 21:26 UTC, SanyaSemenov commented on src/state.ts
> +            let newId:number = state.events.length ? state.events[state.events.length-1].id+1 : 0;
надежнее сделать проверку так `state.events?.length ? ...`

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEvent.tsx
> +        const eventInput = document.getElementById('eventInput') as HTMLInputElement;
и логика очистки формы тоже должна быть в ее компоненте

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEvent.tsx
> +    setOpen(isOpen){
красивее вот так)
```typescript
setOpen(open: boolean): void {
    this.setState(()=>({open}));
}
```

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEvent.tsx
> +    addEvent(addEventFunc){
ой-ёй-ёй а тут нельзя без передачи функции в качестве аргумента?
(не забывай про типизацию)
```typescript
addEvent(addEventFunc: (event:string)=>void): void {
```

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/Events.tsx
>      let elementDayMonthYear = elementDate.split('.');
elementDate по-хорошему сделать однозначным объектом типа TDate, Date или того типа, что возвращает dayjs, и из этой даты вытаскивать отдельно дни, месяцы и тд (вместо сплита и обращения к массиву по индексу)

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEvent.tsx
> +                        <Button id="addEvent" sx={{width:'50%'}} onClick={()=>this.addEvent(this.props.addEvents.addEventFunction)}>Добавить</Button>
если `addEvent` сделать стрелочной функцией, не придется делать здесь функцию-пустышку, можно будет сразу к ней обращаться

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEvent.tsx
> +                        <Button id="addEvent" sx={{width:'50%'}} onClick={()=>this.addEvent(this.props.addEvents.addEventFunction)}>Добавить</Button>
`id="addEvent"` у тебя `addEvent` и айдишник, и название метода, лучше называть по разному

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEvent.tsx
> +                <Snackbar open={this.state.open} autoHideDuration={3000} onClose={this.handleClose}>
3000 лучше выносить в `readonly` свойство класса
```typescript
readonly snackbarDisplayTime = 3000;
```
```html
autoHideDuration={this.snackbarDisplayTime}
```

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEventForm.tsx
> +                            disabled
неочевидная логика, но пусть так будет - некритично

2023-04-08 21:26 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEventForm.tsx
ты имеешь в виду `<form>`? Так было бы правильнее

2023-04-08 21:26 UTC, SanyaSemenov commented on src/state.ts
> +            let newId:number = state.events.length ? state.events[state.events.length-1].id+1 : 0;
как раз на случай, когда ты будешь использовать localStorage

2023-04-11 21:13 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEvent.tsx
> +    addEvent=()=>{
[nit] на будущее: для такого типизация выглядит вот так `addEvent = (): void => {` или `addEvent: () => void = () => {`

[nit] или [nitpick] означает, что комментарий не обязательно требует исполнения

2023-04-11 21:14 UTC, SanyaSemenov commented on src/components/main/events/addEvent/AddEvent.tsx
> +            this.props.addEvents.changeFormValue('')
[nit] все таки оставил очистку тут)

2023-04-11 21:21 UTC, SanyaSemenov commented on src/state.ts
> +            RenderPage(root);
[nit] такое ощущение, что везде в таких местах не стоит прокидывать весь root, можно как то обходить такое и рендерить отдельный компонент (на будущее изучи). То же касается и единого state для всего приложения, посмотри, как его можно поделить на отдельные

2023-04-11 21:24 UTC, SanyaSemenov commented on src/components/main/events/Events.tsx
> +            isCurrentDate(dayjs(el.date) , date.currentDay, date.currentMonth, date.currentYear),
[nit] почти правильно, но `el.date` уже должен быть типа `dayjs.Dayjs`

2023-04-11 21:26 UTC, SanyaSemenov approved these changes

2023-04-12 14:00 UTC, merged